### ISSUE TITLE
Scrolling is broken on webpage.

### ISSUE THREAD

**Issue by Hailfire805** [DarkIntaqt/challenges#108]
![image](https://user-images.githubusercontent.com/70313918/200100643-3c50ccd6-a3b4-472a-ae1c-6d8026f9f6e8.png)
![image](https://user-images.githubusercontent.com/70313918/200100655-fe26e576-d0a5-441f-a4ec-404913ec6970.png)

**Comment by DarkIntaqt** [comment]
I had this issue before due to some cookie blocking addons. Are you using some of these? 
I tried to fix it by enabling scroll even if cookies aren't accepted, maybe it will work now. 
Thanks for reporting this issue

**Comment by Hailfire805** [comment]
It looks like scrolling works again
