### ISSUE TITLE
ADD: Leaderboards are enabled/disabled for this challenge

### ISSUE THREAD

**Issue by DarkIntaqt** [DarkIntaqt/challenges#130]
See title

**Comment by BlossomiShymae** [comment]
Should it be an an alert card with an info/warning icon and content stating whether the leaderboard is enabled/disabled?

What kind of challenges would have their leaderboards disabled? The seasonal challenges that have ended (2022)? (。ヘ°)

I'll see if I can totes start a pull request on this~*

**Comment by DarkIntaqt** [comment]
Currently only a very few challenges are actually disabled. The 2022 ones are retired. It would be pretty cool if a retired alert / card was shown, but it is currently not supported by the static data generator https://github.com/DarkIntaqt/lolassethelper/issues/2

I would add the disclaimer / alert / card directly into the leaderboard section and suppress showing leaderboards (even tho there shouldn't be leaderboards anyways, but who knows). Otherwise, the disclaimer can be shown like below or in the info section. 

Feel free to PR if you are feeling to do so ^^ - a disabled challenge to test is "everything but the kitchen sink"

**Comment by DarkIntaqt** [comment]
Update: RETIRED and DISABLED states are added https://github.com/DarkIntaqt/lolassethelper/issues/2 and uploaded to next/live.

**Comment by BlossomiShymae** [comment]
Thoughts on the alert card I made? <sub><sup>aaaaaaa</sup></sub>

![image](https://user-images.githubusercontent.com/87099578/231514064-825f16c6-e55d-4030-937a-3fd28d19b3af.png)

**Comment by DarkIntaqt** [comment]
I would center the text, otherwise it looks great ^^

**Comment by BlossomiShymae** [comment]
> It would be pretty cool if a retired alert / card was shown, but it is currently not supported by the static data generator [DarkIntaqt/lolassethelper#2](https://github.com/DarkIntaqt/lolassethelper/issues/2)

Should I go ahead and add this in a separate pull request or in the same one (since the `RETIRED` state was added as well)? 
I am okie dokie with this one too!

![3133_EM_Event_AprilFools_First_Blood_Inventory_100x100 blossoms](https://user-images.githubusercontent.com/87099578/231556513-9dc13cc7-375e-4faf-ba99-b44e9870fabd.png)

**Comment by DarkIntaqt** [comment]
Feel free to add it to the current PR. Please keep in mind that retired challenges DO have leaderboards, so maybe add retired as a tag (below the title) or so :)

**Comment by BlossomiShymae** [comment]
Something like this maybe? o.o
![image](https://user-images.githubusercontent.com/87099578/231565303-7d91f10d-718c-46b7-b822-42eaa5529f87.png)
