### ISSUE TITLE
Contrast accessibility issues with "None" and "Unranked" color text

### ISSUE THREAD

**Issue by BlossomiShymae** [DarkIntaqt/challenges#138]
Hi! ⋆˙⟡♡

There appears to be text across the site that can be very hard to see with the font color used.
![image](https://user-images.githubusercontent.com/87099578/218895075-478577bd-9999-453f-808f-b7aeacc68dc9.png)
![image](https://user-images.githubusercontent.com/87099578/218895249-0fdfe222-84ac-455d-b270-0a8971a1a4ce.png)

**Comment by DarkIntaqt** [comment]
#139
