### ISSUE TITLE
Challenge tracker does not let me verify myself

### ISSUE THREAD

**Issue by HyperLexus** [DarkIntaqt/challenges#160]
I have looked myself up, I tried enabling the history feature, signed in, did the riot verification thing, and it then returned "Error: User not found" at https://challenges.darkintaqt.com/verify?step=league&verify. I don't know why, I did everything correctly.

**Comment by HyperLexus** [comment]
> Sad to hear that this happened! Can you give me your summoner name and server? I can enable the verification manually for you if you want and in the meantime I will have a look at the error message

Thank you, I appreciate it! Summoner name HyperLexus, Server EUW.

**Comment by DarkIntaqt** [comment]
I have verified you and the bug shouldn't happen again. Thank you for reporting this issue!
