### ISSUE TITLE
Start page displaying wrong date for `Something special will happen...`

### ISSUE THREAD

**Issue by BlossomiShymae** [DarkIntaqt/challenges#164]
Hii! ^w^

See title.
![image](https://user-images.githubusercontent.com/87099578/235165827-ca84bc00-7ed6-46f1-ad55-2b45202fec11.png)

EDIT:
It wasn't the wrong date, it was just displayed incorrectly since it was in the wrong format. (〃▽〃)

**Comment by DarkIntaqt** [comment]
Woops thanks a lot for fixing this ^^
I try to deploy it as soon as possible :)
