### ISSUE TITLE
`Missing match file. Maybe it is malformed?` - Summoner History

### ISSUE THREAD

**Issue by 1337MARCEL** [DarkIntaqt/challenges#172]
In [my](https://challenges.darkintaqt.com/euw/mvrcel/history) history, all my recent matches look like the below. Is this a known issue? 👀 

![image](https://github.com/DarkIntaqt/challenges/assets/16888873/e5222fce-0be5-4c73-ab3e-a5547a267e8f)

**Comment by renja-grotemeyer** [comment]
Hmm, now that you say it, I also have some matches with the error (a lot)

**Comment by DarkIntaqt** [comment]
Hi!
Thanks for pointing this out. 
The initial issue is resolved, new matches are going to be added just fine. Luckily, the historical qchallenge stats aren't gone, which are hard to recover without the client itself ^^. 
The old, missing matches will be re-fetched now, that can take a while.

**Comment by DarkIntaqt** [comment]
Everything should be resolved now. Feel free to reopen this issue if the problem is reoccurring :)
