### ISSUE TITLE
Terms of Service page stuck on `Loading...` modal window after CORS policy error

### ISSUE THREAD

**Issue by BlossomiShymae** [DarkIntaqt/challenges#174]
Hiii again! 

![__cirno_touhou_drawn_by_rei_tonbo0430__sample-6424e489f672536e873d9c509fdab558](https://github.com/DarkIntaqt/challenges/assets/87099578/d138130e-4ea2-4ea5-897b-bd8e41e0f1b5)

Trying to access https://challenges.darkintaqt.com/tos results in an un-closeable modal window that blocks seeing the terms of service. I'm using the English language setting and it happens in both Mozilla Firefox and Microsoft Edge.

Could it be due to the failed XHR for `CORS Missing Allow Origin`?

![image](https://github.com/DarkIntaqt/challenges/assets/87099578/8484b56c-d759-406b-aea6-613e20faa20f)

![image](https://github.com/DarkIntaqt/challenges/assets/87099578/89143b84-de75-451a-bc84-b70c5453b4b8)

**Comment by DarkIntaqt** [comment]
Thanks a lot for reporting this. 
The site was still using an old consent manager which was loading a file which didn't exist anymore. I replaced the script tag.
