### ISSUE TITLE
Sorting by Leaderboard Position sorts some unranked challenges incorrectly

### ISSUE THREAD

**Issue by Scead64** [DarkIntaqt/challenges#180]
For any category, if I am unranked in a challenge it may incorrectly display "top 0%" even though it should be "top 100%" given I am unranked in the challenge. 

![Challenge-site issue 1 1](https://github.com/DarkIntaqt/challenges/assets/95952790/18fe8dbb-0b54-4400-a551-703018795a52)
![Challenge-site issue 1 2](https://github.com/DarkIntaqt/challenges/assets/95952790/444fcb0e-ffde-4acf-8a29-f54062a1c384)
![Challenge-site issue 1 3](https://github.com/DarkIntaqt/challenges/assets/95952790/59d5b4f5-7dad-4d68-8f4b-b1b6e86c831f)

**Comment by DarkIntaqt** [comment]
Thanks for reporting this. It should be fixed by now
