### ISSUE TITLE
Challenge Points Leaderboard doesn't show users with the same amount of points

### ISSUE THREAD

**Issue by TrusTio** [DarkIntaqt/challenges#212]
The leaderboard doesn't show users with the same number of points. None of the users in the leaderboard have repeating points
I stumbled on this as I was previously on the eune leaderboard, but as soon as I hit 22.095 points, I disappeared. There's someone else with the same exact points. Checked for any duplicate points across the leaderboard and there are none, I'd figure there would be at least some considering it gets harder and harder to get points after you reach 21-22k

**Comment by DarkIntaqt** [comment]
I will have a look, thanks for the report

**Comment by DarkIntaqt** [comment]
Hi, have you swapped servers by any chance recently?

**Comment by TrusTio** [comment]
I swapped from EUW about half a year ago. I messaged you on twitter to send you a screenshot a few minutes ago, but it was already resolved. Not sure why my user disappeared earlier today when I earned some extra points, but it's back again now.

**Comment by DarkIntaqt** [comment]
I will close this as it seems to be resolved. Feel free to reopen this issue or create a new one
