### ISSUE TITLE
Allow to get detailes information for challenges tracking specific characters

### ISSUE THREAD

**Issue by Porkepix** [DarkIntaqt/challenges#225]
This apply among other things to:
- Top Performer
- All Random All Flawless
- Adapt to All Situations
- Champion Ocean

All these challenges tracks every champion and for anyone who cares about getting them, it's a pain to track them: you need to either regularly takes many screenshot or keep a list you update yourself in a file as those information are available in the client only in the Challenges pages but not when you pick a Champion.
Be able to see these information from the website automatically up to date would be of great help as one would just have to look at it during picks for example.

(A little bit out of the topic of the challenges, but be able to track the new chests unlock system the same way would be quite useful as that's not visible when we pick our character either!)

**Comment by DarkIntaqt** [comment]
Hi,
thanks for the suggestion. Unfortunately, it is not possible for me (as the website) to display these information, as they are just not available. So the only option would be to have a manual list. 
The same applies to the chest available topic, sorry to disappoint you
