### ISSUE TITLE
Challenge tracker does not let me verify myself

### ISSUE THREAD

**Issue by Kien1804** [DarkIntaqt/challenges#252]
Sad to hear that this happened! Can you give me your summoner name and server? I can enable the verification manually for you if you want and in the meantime I will have a look at the error message
duc anh le #77777 ( VN  )

**Comment by DarkIntaqt** [comment]
Hi, thanks for reporting this bug. Riot Games has currently some issues going on with RSO ( https://github.com/RiotGames/developer-relations/issues/999 ), so I will verify you manually. 
Have a nice day
