### ISSUE TITLE
Add absolute date to last upgraded tab

### ISSUE THREAD

**Issue by phenomist** [DarkIntaqt/challenges#67]
Sorry if there is a better way to request a feature. Would it be possible (perhaps via mouseover) to get the absolute date e.g. 2022-05-31 (not a relative date like "2 months ago", which is much less precise) when on the Last upgraded tab? I'm trying to fill in some historical stuff for my personal challenge tracking spreadsheet. Thanks!

**Comment by DarkIntaqt** [comment]
That is the exact place to request a feature and your idea sounds great! That is just a really small change, I will add it tomorrow. 
Checklist for me
- [ ] react-timestamps update
- [ ] Timestamp component attribute type=static
- [ ] Add an hover/click switch listener, maybe even update react-timestamps for this. 
Thanks for your idea!

**Comment by DarkIntaqt** [comment]
I added it and rebuild the page, maybe you need to reload the page once to see the changes.
