### ISSUE TITLE
Summoner not being found with a special greek character

### ISSUE THREAD

**Issue by halilbahar** [DarkIntaqt/challenges#82]
The summoner name `Y Ξ` can not be found with the API.
I tried the following without success:
* `https://challenges.darkintaqt.com/api/v3/u/?name=Y%20%CE%9E&server=euw`
* `https://challenges.darkintaqt.com/api/v3/u/?name=Y%CE%9E&server=euw`

Seems like the api cannot handle this greek character. I tried a name with the german `ö` and it worked.

Here is a working example of u.gg:
`https://u.gg/lol/profile/euw1/Y%20%CE%9E/overview`

**Comment by DarkIntaqt** [comment]
fixed it:
https://challenges.darkintaqt.com/euw/Y%20Ξ

The problem was, that the server thought it was a troll name, as it is (without the whitespace) not 3 characters long. I lowered the threshold.

**Comment by halilbahar** [comment]
tyvm :)
