### ISSUE TITLE
save search params of /challenges

### ISSUE THREAD

**Issue by DarkIntaqt** [DarkIntaqt/challenges#90]

**Comment by BlossomiShymae** [comment]
Hii! :3

I'm thinking of submitting a PR for this feature but I'm not totes sure on what you mean.
Do you mean persisting the state of this search input here for `/challenges`? 

![image](https://user-images.githubusercontent.com/87099578/218638770-615ef0b8-e6aa-4c71-badb-54595e2d104f.png)

Does this also include the challenge filters as well?

**Comment by DarkIntaqt** [comment]
Hi ^^
Yup, "No description provided" is of course not very helpful. 

So I thought about persisting the state of the search input on the top and the filters on the side when returning to the site (probably without reloading). I think that can be helpful if you want to search challenges within a specific scope (e.g. you are searching for "kills") and if the first challenge is not what you want you don't have to apply all filters again.
